services:
  read-server:
    image: ghcr.io/otwako/qyd-reader-docker:latest
    container_name: qyd-reader
    restart: unless-stopped
    ports:
      - ":8080"
    volumes:
      # REQUIRED: Mount and override with your configuration file
      - ./conf.yml:/app/conf.yml
      # OPTIONAL: Mount storage for local books/covers if needed
      - ./data:/app
    environment:
      - TZ=Asia/Taipei